apiVersion: v1
kind: Service
metadata:
  name: crate-internal-service
  namespace: pioneers
  labels:
    app: crate
    demo_set: "superset-cratedb"
spec:
  # A static IP address is assigned to this service. This IP address is
  # only reachable from within the Kubernetes cluster.
  type: ClusterIP
  ports:
    # Port 4300 for inter-node communication.
  - port: 4300
    name: crate-internal
  selector:
    # Apply this to all nodes with the `app:crate` label.
    app: crate
---
apiVersion: v1
kind: Service
metadata:
  name: crate-external-svc
  namespace: pioneers
  labels:
    app: crate
    demo_set: "superset-cratedb"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: crate-pioneers.bregenz.a1.cratedb.net
spec:
  # Create an externally reachable load balancer.
  type: LoadBalancer
  ports:
    # Port 4200 for HTTP clients.
  - port: 4200
    name: crate-web
    # Port 5432 for PostgreSQL wire protocol clients.
  - port: 5432
    name: postgres
  selector:
    # Apply this to all nodes with the `app:crate` label.
    app: crate
---
apiVersion: v1
kind: Service
metadata:
  name: redis-internal-svc
  namespace: pioneers
  labels:
    app: redis
    demo_set: "superset-cratedb"
spec:
  # A static IP address is assigned to this service. This IP address is
  # only reachable from within the Kubernetes cluster.
  type: ClusterIP
  ports:
    # Port 6379 for Redis.
  - port: 6379
    name: redis-internal
  selector:
    # Apply this to all nodes with the `app:redis` label.
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    demo_set: "superset-cratedb"
  name: postgres
  namespace: pioneers
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    demo_set: "superset-cratedb"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: superset-pioneers.bregenz.a1.cratedb.net
  name: superset
  namespace: pioneers
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    io.kompose.service: superset
status:
  loadBalancer: {}
---
