kind: PersistentVolume
apiVersion: v1
metadata:
  name: superset2-pv
  labels:
    type: local
    app: superset2
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"