kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: superset
  labels:
    type: local
    app: superset2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi