kind: Namespace
apiVersion: v1
metadata:
  name: pioneers
  labels:
    project_friendly_name: "pioneer"
    in_question_contact: "gianluca"
    demo_set: "superset-cratedb"
spec:
  finalizers:
  - kubernetes