apiVersion: v1
kind: Service
metadata:
  name: crate-external-svc
  namespace: pioneers
  labels:
    app: crate
    demo_set: "superset-cratedb"
  #annotations:
  #  external-dns.alpha.kubernetes.io/hostname: crate-pioneers.bregenz.a1.cratedb.net
spec:
  # Create an externally reachable load balancer.
  type: LoadBalancer
  ports:
    # Port 4200 for HTTP clients.
  - port: 4200
    name: crate-web
    # Port 5432 for PostgreSQL wire protocol clients.
  - port: 5432
    name: postgres
  selector:
    # Apply this to all nodes with the `app:crate` label.
    app: crate
