apiVersion: v1
kind: Service
metadata:
  name: redis-internal-svc
  namespace: pioneers
  labels:
    app: redis
spec:
  # A static IP address is assigned to this service. This IP address is
  # only reachable from within the Kubernetes cluster.
  type: ClusterIP
  ports:
    # Port 6379 for Redis.
  - port: 6379
    name: redis-internal
  selector:
    # Apply this to all nodes with the `app:redis` label.
    app: redis
