apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: pioneers
  labels:
    demo_set: "superset-cratedb"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - image: redis
        name: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /redis-data
          name: data
        - mountPath: /redis
          name: config
      restartPolicy: Always
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf
status: {}
