apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    demo_set: "superset-cratedb"
  name: postgres
  namespace: pioneers
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP