apiVersion: v1
kind: Service
metadata:
  labels:
    demo_set: "superset-cratedb"
  #annotations:
  #  external-dns.alpha.kubernetes.io/hostname: crate-pioneers.bregenz.a1.cratedb.net
  name: superset
  namespace: pioneers
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    io.kompose.service: superset
status:
  loadBalancer: {}
