apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  # This is the name used as a prefix for all pods in the set.
  name: superset
  namespace: pioneers
spec:
  serviceName: "superset-set"
  # Our cluster has three nodes.
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: amancevice/superset
        command: ["/bin/bash"]
        args: ["/home/superset/init_superset.sh" ]
        volumeMounts:
        - mountPath: /etc/superset/superset_config.py
          subPath: superset_config.py
          name: config-volume
        - mountPath: /home/superset/init_superset.sh
          subPath: init_superset.sh
          name: config-volume
        resources:
          limits:
            # How much memory each pod gets.
            memory: 500Mi
        ports:
          # Port 4200 for HTTP clients.
        - containerPort: 8088
          name: superset-web
      volumes:
      - name: config-volume
        configMap:
          name: superset-config
  volumeClaimTemplates:
    # Use persistent storage.
    - metadata:
        name: superset-data
      spec:
        #probably change storageclassname this before running in bregenz
        storageClassName: standard
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
